alias lgit="ls --git"

alias gs="git status -sb"
alias gco="git checkout"
alias ga="git add"
alias gaa="git add -A"
alias gc="git commit"
alias gca="git commit --amend"
alias gph="git push"
alias gpl="git pull"
alias gdf="git diff"
alias gl="git log --oneline --graph --decorate --all"
alias gch="git fetch ; git status"
alias grs="git remote show origin"

alias ch="chezmoi"
alias chad="chezmoi add"
alias chap="chezmoi apply"
alias chd="chezmoi diff"
alias chda="chezmoi data"
alias chs="chezmoi status"
alias che="chezmoi edit"

alias b="bat"
alias bp="bat --plain"
alias bn="bat --paging=never"
alias bpn="bn --plain"

alias s="paru -Ss"
alias sm="pacman -Ss"
alias i="paru -S"
alias u="paru -Syu"
alias uy="paru -Syy"
alias r="paru -Rns"
alias ie="paru -Qqe"
alias iea="paru -Q"

alias ma="matugen"
alias mai="matugen image"
alias mais="matugen image --show-colors"
alias maig="matugen --config ~/.config/matugen/config-gtk.toml image"
alias maigs="matugen --config ~/.config/matugen/config-gtk.toml image --show-colors"

alias change="$EDITOR ~/.config/fish/"
alias niri-ch="$EDITOR ~/.config/niri/"
alias sync="xclip -o | wl-copy"
