cursor #f0dfd8
cursor_text_color #d7c2b9

foreground            #f0dfd8
background            #1a120e
selection_foreground  #432a1e
selection_background  #e6beac
url_color             #ffb692

color0 #1a1a1a
color1 #e24a82
color2 #99d66e
color3 #dbac7b
color4 #bf7048
color5 #bf937d
color6 #ffb692
color7 #abb1bf
color8 #5c6270
color9 #e05f91
color10 #abe086
color11 #e8c097
color12 #ffc29b
color13 #b66454
color14 #9b7352
color15 #ffffff
