# Fonts Settings
# font_family      family="JetBrainsMono Nerd Font Mono" style=Bold
# bold_font        family='JetBrainsMono Nerd Font Mono' style=Bold
# italic_font      auto
# bold_italic_font auto

include ./theme.conf
include ./kitty-colors.conf

font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
# too bold for font
text_composition_strategy legacy
font_size 11.0

shell_integration no-cursor

cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0

background_opacity 0.8
background_blur 0

confirm_os_window_close 0

map ctrl+plus         change_font_size all +2.0
map ctrl+minus        change_font_size all -2.0
map ctrl+0            change_font_size all 0
map shift+PAGE_UP     scroll_page_up
map shift+PAGE_DOWN   scroll_page_down

map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+enter launch --cwd=current
map ctrl+shift+n new_os_window_with_cwd
# hide_window_decorations yes
